name: Christmasden.com
favicon: null
layout_spectrum: 0.7947163949720562
typography_spectrum: 0.8843242567963898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.45795055921189487
  lightness: 0.3080406740773469
  saturation: 0.7448056337889284
  rhythmicContrast: 0.7569576154928654
purpose: []
